var Jugadors=[
{nom:"Aina",     path:"img/aina.jpg"},
{nom:"Alba",     path:"img/alba.jpg"},
{nom:"Diana",    path:"img/diana.jpg"},
{nom:"Fede",     path:"img/fede.jpg"},
{nom:"Frans",    path:"img/frans.jpg"},
{nom:"Jaume",    path:"img/jaume.jpg"},
{nom:"Laura",    path:"img/laura.jpg"},
{nom:"Lluís",    path:"img/lluis.jpg"},
{nom:"Màrius",   path:"img/marius.jpg"},
{nom:"Núria",    path:"img/nuria.jpg"},
{nom:"Paton",    path:"img/paton.jpg"},
{nom:"Queralt",  path:"img/queralt.jpg"},
{nom:"Rosa",     path:"img/rosa.jpg"},
{nom:"Rut",      path:"img/rut.jpg"},
{nom:"Sandra",   path:"img/sandra.jpg"},
{nom:"Àlex",     path:"img/alex.jpg"},
];
